### PR TITLE
Bump dependencies to their latest versions 

### LINKED ISSUE #89: Lastest versions of stdlib and apt modules are not supported
Hi,

The latest version (1.0.0) is not compatible with the latest versions of stdlib and apt.

This module requires a version below 5.0.0 for both stdlib and apt, which have a latest version of 6.0.0 and 7.0.1 respectively.

Thanks,
Jory

### PR DESCRIPTION
**Pull request by vStone**
Fixes #89

### CODE REVIEW

**Review by jormaster3k — APPROVED** [review]

**Comment by unrulyv** [comment]
Hi there, we'd like to use this puppet-aptly module, but this dependency issue is blocking us from being able to deploy in production. In testing, the module works fine with newer puppetlabs-apt and puppetlabs-stdlib. Can this be merged please?

**Comment by sid3windr** [comment]
Same issue here, works with --force override on test.

**Comment by sengi** [comment]
Apologies for the lack of response on this, and the inconvenience of working around the version constraints. As you've probably assumed by now, this repo is effectively without a maintainer.

Happy to merge this if folks are still using this module.

Bit of background in case it's helpful to those here or anyone else who finds this: we (GDS / GOV.UK) expect the last of our Puppet-managed services to have moved onto Kubernetes within the next few months. We also no longer have a critical mass of people who know Puppet at GDS, so it's unlikely we'll be able to maintain this repo for much longer. (I'll be happy to do what I can to facilitate a smooth transition if anyone here wants to maintain a fork of this repo after it's archived in alphagov.)

**Review by sengi — APPROVED** [review]

**Comment by sengi** [comment]
Hi there, folks. Sorry to be the bearer of bad news, but we don't actually have anyone maintaining this repo any more as we no longer run Puppet. I'm about to archive this and a bunch of other Puppet-related repos that we haven't touched in a long time.

It's no longer feasible for us to accept contributions at this point as we no longer have enough reviewers on our side who can review Puppet. I realise this must be extra frustrating since you already have one approval, but I'd need a second Puppet reviewer on our side, which we no longer have.

My apologies that we haven't signposted that we're no longer set up to receive outside contributions.

You're most welcome to fork, of course — not that that's much consolation. I'm sorry to be the bearer of bad news. I really appreciate that you want to contribute here and I'm sad that I can't help make that happen on this occasion 😞

**Pull request closed without merging**
